[package]
name = "reth-verkle-trie"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Verkle trie implementation"

[lints]
workspace = true

[dependencies]
once_cell = "1.8.0"
hex = "0.4.3"

#rust-verkle
verkle-trie = { git = "https://github.com/crate-crypto/rust-verkle.git" }
banderwagon = { git = "https://github.com/crate-crypto/rust-verkle.git" }
